FROM node:22.4.0-bookworm-slim AS deps

WORKDIR /usr/app/src

RUN npm install -g npm@10.2.1
RUN npm install -g @bufbuild/buf @bufbuild/protoc-gen-es @connectrpc/protoc-gen-connect-es && \
    npm install -g @connectrpc/connect @bufbuild/protobuf

COPY buf.gen.yaml .

CMD ["npx", "buf", "generate"]
