// source: k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb = require('../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.js');
goog.object.extend(proto, k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb);
var k8s_io_apimachinery_pkg_runtime_schema_generated_pb = require('../../../../../../k8s.io/apimachinery/pkg/runtime/schema/generated_pb.js');
goog.object.extend(proto, k8s_io_apimachinery_pkg_runtime_schema_generated_pb);
goog.exportSymbol('proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.repeatedFields_, null);
};
goog.inherits(proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.displayName = 'proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.toObject = function(opt_includeInstance) {
  return proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.ListMeta.toObject(includeInstance, f),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.PartialObjectMetadata.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList;
  return proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.ListMeta;
      reader.readMessage(value,k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.ListMeta.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 1:
      var value = new k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.PartialObjectMetadata;
      reader.readMessage(value,k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.PartialObjectMetadata.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.ListMeta.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.PartialObjectMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta metadata = 2;
 * @return {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.getMetadata = function() {
  return /** @type{?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta} */ (
    jspb.Message.getWrapperField(this, k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.ListMeta, 2));
};


/**
 * @param {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta|undefined} value
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} returns this
*/
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} returns this
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata items = 1;
 * @return {!Array<!proto.k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata>}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata>} */ (
    jspb.Message.getRepeatedWrapperField(this, k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.PartialObjectMetadata, 1));
};


/**
 * @param {!Array<!proto.k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata>} value
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} returns this
*/
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata}
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.k8s.io.apimachinery.pkg.apis.meta.v1.PartialObjectMetadata, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList} returns this
 */
proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1.PartialObjectMetadataList.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


goog.object.extend(exports, proto.k8s.io.apimachinery.pkg.apis.meta.v1beta1);
