// Copyright 2023 DR
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=.ts"
// @generated from file sk8l.proto (package sk8l, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CronjobPodsRequest, CronjobPodsResponse, CronjobRequest, CronjobResponse, CronjobsRequest, CronjobsResponse, CronjobYAMLResponse, DashboardAnnotationsRequest, DashboardAnnotationsResponse, JobRequest, JobYAMLResponse, PodRequest, PodYAMLResponse } from "./sk8l_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sk8l.Cronjob
 */
export const Cronjob = {
  typeName: "sk8l.Cronjob",
  methods: {
    /**
     * @generated from rpc sk8l.Cronjob.GetCronjobs
     */
    getCronjobs: {
      name: "GetCronjobs",
      I: CronjobsRequest,
      O: CronjobsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc sk8l.Cronjob.GetCronjob
     */
    getCronjob: {
      name: "GetCronjob",
      I: CronjobRequest,
      O: CronjobResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc sk8l.Cronjob.GetCronjobPods
     */
    getCronjobPods: {
      name: "GetCronjobPods",
      I: CronjobPodsRequest,
      O: CronjobPodsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc sk8l.Cronjob.GetCronjobYAML
     */
    getCronjobYAML: {
      name: "GetCronjobYAML",
      I: CronjobRequest,
      O: CronjobYAMLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sk8l.Cronjob.GetJobYAML
     */
    getJobYAML: {
      name: "GetJobYAML",
      I: JobRequest,
      O: JobYAMLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sk8l.Cronjob.GetPodYAML
     */
    getPodYAML: {
      name: "GetPodYAML",
      I: PodRequest,
      O: PodYAMLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sk8l.Cronjob.GetDashboardAnnotations
     */
    getDashboardAnnotations: {
      name: "GetDashboardAnnotations",
      I: DashboardAnnotationsRequest,
      O: DashboardAnnotationsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

