// source: sk8l_custom.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb = require('./k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.js');
goog.object.extend(proto, k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb);
var k8s_io_api_batch_v1_generated_pb = require('./k8s.io/api/batch/v1/generated_pb.js');
goog.object.extend(proto, k8s_io_api_batch_v1_generated_pb);
goog.exportSymbol('proto.sk8l_custom.JobStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sk8l_custom.JobStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.sk8l_custom.JobStatus.repeatedFields_, null);
};
goog.inherits(proto.sk8l_custom.JobStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sk8l_custom.JobStatus.displayName = 'proto.sk8l_custom.JobStatus';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sk8l_custom.JobStatus.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sk8l_custom.JobStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.sk8l_custom.JobStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sk8l_custom.JobStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sk8l_custom.JobStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    conditionsList: jspb.Message.toObjectList(msg.getConditionsList(),
    k8s_io_api_batch_v1_generated_pb.JobCondition.toObject, includeInstance),
    starttime: (f = msg.getStarttime()) && k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time.toObject(includeInstance, f),
    completiontime: (f = msg.getCompletiontime()) && k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time.toObject(includeInstance, f),
    active: jspb.Message.getFieldWithDefault(msg, 4, 0),
    succeeded: jspb.Message.getFieldWithDefault(msg, 5, 0),
    failed: jspb.Message.getFieldWithDefault(msg, 6, 0),
    terminating: jspb.Message.getFieldWithDefault(msg, 11, 0),
    completedindexes: jspb.Message.getFieldWithDefault(msg, 7, ""),
    failedindexes: jspb.Message.getFieldWithDefault(msg, 10, ""),
    uncountedterminatedpods: (f = msg.getUncountedterminatedpods()) && k8s_io_api_batch_v1_generated_pb.UncountedTerminatedPods.toObject(includeInstance, f),
    ready: jspb.Message.getFieldWithDefault(msg, 9, 0),
    starttimeins: jspb.Message.getFieldWithDefault(msg, 880, 0),
    completiontimeins: jspb.Message.getFieldWithDefault(msg, 881, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sk8l_custom.JobStatus}
 */
proto.sk8l_custom.JobStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sk8l_custom.JobStatus;
  return proto.sk8l_custom.JobStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sk8l_custom.JobStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sk8l_custom.JobStatus}
 */
proto.sk8l_custom.JobStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new k8s_io_api_batch_v1_generated_pb.JobCondition;
      reader.readMessage(value,k8s_io_api_batch_v1_generated_pb.JobCondition.deserializeBinaryFromReader);
      msg.addConditions(value);
      break;
    case 2:
      var value = new k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time;
      reader.readMessage(value,k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time.deserializeBinaryFromReader);
      msg.setStarttime(value);
      break;
    case 3:
      var value = new k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time;
      reader.readMessage(value,k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time.deserializeBinaryFromReader);
      msg.setCompletiontime(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setActive(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSucceeded(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFailed(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTerminating(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompletedindexes(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailedindexes(value);
      break;
    case 8:
      var value = new k8s_io_api_batch_v1_generated_pb.UncountedTerminatedPods;
      reader.readMessage(value,k8s_io_api_batch_v1_generated_pb.UncountedTerminatedPods.deserializeBinaryFromReader);
      msg.setUncountedterminatedpods(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReady(value);
      break;
    case 880:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarttimeins(value);
      break;
    case 881:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCompletiontimeins(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sk8l_custom.JobStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sk8l_custom.JobStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sk8l_custom.JobStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sk8l_custom.JobStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConditionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      k8s_io_api_batch_v1_generated_pb.JobCondition.serializeBinaryToWriter
    );
  }
  f = message.getStarttime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time.serializeBinaryToWriter
    );
  }
  f = message.getCompletiontime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getUncountedterminatedpods();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      k8s_io_api_batch_v1_generated_pb.UncountedTerminatedPods.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getStarttimeins();
  if (f !== 0) {
    writer.writeInt64(
      880,
      f
    );
  }
  f = message.getCompletiontimeins();
  if (f !== 0) {
    writer.writeInt64(
      881,
      f
    );
  }
};


/**
 * repeated k8s.io.api.batch.v1.JobCondition conditions = 1;
 * @return {!Array<!proto.k8s.io.api.batch.v1.JobCondition>}
 */
proto.sk8l_custom.JobStatus.prototype.getConditionsList = function() {
  return /** @type{!Array<!proto.k8s.io.api.batch.v1.JobCondition>} */ (
    jspb.Message.getRepeatedWrapperField(this, k8s_io_api_batch_v1_generated_pb.JobCondition, 1));
};


/**
 * @param {!Array<!proto.k8s.io.api.batch.v1.JobCondition>} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
*/
proto.sk8l_custom.JobStatus.prototype.setConditionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.k8s.io.api.batch.v1.JobCondition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.k8s.io.api.batch.v1.JobCondition}
 */
proto.sk8l_custom.JobStatus.prototype.addConditions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.k8s.io.api.batch.v1.JobCondition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearConditionsList = function() {
  return this.setConditionsList([]);
};


/**
 * optional k8s.io.apimachinery.pkg.apis.meta.v1.Time startTime = 2;
 * @return {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.Time}
 */
proto.sk8l_custom.JobStatus.prototype.getStarttime = function() {
  return /** @type{?proto.k8s.io.apimachinery.pkg.apis.meta.v1.Time} */ (
    jspb.Message.getWrapperField(this, k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time, 2));
};


/**
 * @param {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.Time|undefined} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
*/
proto.sk8l_custom.JobStatus.prototype.setStarttime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearStarttime = function() {
  return this.setStarttime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasStarttime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional k8s.io.apimachinery.pkg.apis.meta.v1.Time completionTime = 3;
 * @return {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.Time}
 */
proto.sk8l_custom.JobStatus.prototype.getCompletiontime = function() {
  return /** @type{?proto.k8s.io.apimachinery.pkg.apis.meta.v1.Time} */ (
    jspb.Message.getWrapperField(this, k8s_io_apimachinery_pkg_apis_meta_v1_generated_pb.Time, 3));
};


/**
 * @param {?proto.k8s.io.apimachinery.pkg.apis.meta.v1.Time|undefined} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
*/
proto.sk8l_custom.JobStatus.prototype.setCompletiontime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearCompletiontime = function() {
  return this.setCompletiontime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasCompletiontime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 active = 4;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getActive = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setActive = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearActive = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasActive = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 succeeded = 5;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getSucceeded = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setSucceeded = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearSucceeded = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasSucceeded = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 failed = 6;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getFailed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setFailed = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearFailed = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasFailed = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 terminating = 11;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getTerminating = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setTerminating = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearTerminating = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasTerminating = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string completedIndexes = 7;
 * @return {string}
 */
proto.sk8l_custom.JobStatus.prototype.getCompletedindexes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setCompletedindexes = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearCompletedindexes = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasCompletedindexes = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string failedIndexes = 10;
 * @return {string}
 */
proto.sk8l_custom.JobStatus.prototype.getFailedindexes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setFailedindexes = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearFailedindexes = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasFailedindexes = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional k8s.io.api.batch.v1.UncountedTerminatedPods uncountedTerminatedPods = 8;
 * @return {?proto.k8s.io.api.batch.v1.UncountedTerminatedPods}
 */
proto.sk8l_custom.JobStatus.prototype.getUncountedterminatedpods = function() {
  return /** @type{?proto.k8s.io.api.batch.v1.UncountedTerminatedPods} */ (
    jspb.Message.getWrapperField(this, k8s_io_api_batch_v1_generated_pb.UncountedTerminatedPods, 8));
};


/**
 * @param {?proto.k8s.io.api.batch.v1.UncountedTerminatedPods|undefined} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
*/
proto.sk8l_custom.JobStatus.prototype.setUncountedterminatedpods = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearUncountedterminatedpods = function() {
  return this.setUncountedterminatedpods(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasUncountedterminatedpods = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int32 ready = 9;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getReady = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setReady = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.clearReady = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sk8l_custom.JobStatus.prototype.hasReady = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional int64 startTimeInS = 880;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getStarttimeins = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 880, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setStarttimeins = function(value) {
  return jspb.Message.setProto3IntField(this, 880, value);
};


/**
 * optional int64 completionTimeInS = 881;
 * @return {number}
 */
proto.sk8l_custom.JobStatus.prototype.getCompletiontimeins = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 881, 0));
};


/**
 * @param {number} value
 * @return {!proto.sk8l_custom.JobStatus} returns this
 */
proto.sk8l_custom.JobStatus.prototype.setCompletiontimeins = function(value) {
  return jspb.Message.setProto3IntField(this, 881, value);
};


goog.object.extend(exports, proto.sk8l_custom);
